# welcome to jekyll!
#
# this config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# for technical reasons, this file is *not* reloaded automatically when you use
# `jekyll serve`. if you change this file, please restart the server process.

# site settings
locale                   : "shenzhen, china"
title                    : "zilin wang / master student"
title_separator          : "-"
name                     : &name "zilin wang"
description              : &description "personal homepage"
url                      : https://zerlinwang.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "zerlinwang/zerlinwang.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedfields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitmessage          : "new comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredfields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedfields:
    date:
      type               : "date"
1 change; before #3  12 seconds ago
